### ISSUE TITLE
Peer to peer - Code Review

### ISSUE THREAD

**Issue by DanteAlonsoHT** [DanteAlonsoHT/To_Do_List_webpack#2]
Feel free to give me any feedback to improve the project 😉

**Comment by Hamzaoutdoors** [comment]
# To do list project 

> Good Job @DanteAlonsoHT 🥳 🥳 🥳 🥳 you did a good job!

## Congratulations !!!
 - We couldn't find an issue with your project you did all the requirements for the activity man! Have a great weekend.
