### ISSUE TITLE
To-do-list Issues

### ISSUE THREAD

**Issue by mateo951** [DanteAlonsoHT/To_Do_List_webpack#5]
Your project is well done! I just have a minor suggestion for you 🙌 

I think the code can be improved by using a forEach() statement because its a better js practice 🧐

https://github.com/DanteAlonsoHT/To_Do_List_webpack/blob/e41fe8de5747ef97fe6dee0f5843e3c7b274f6e5/src/checkbox.js#L23-L25

**Comment by memelopez** [comment]
you can use this to import styles 
import './style.css';
